feat: Close channels after three days of being open
discord-math/bot pull request #69
Opened 2024-05-03 01:37 UTC by Brandon-Huu

Untested lmao

2024-05-03 01:49 UTC, rattus-rattus-rattus requested changes
Please refer to [CONTRIBUTING.md](https://github.com/discord-math/bot/blob/main/CONTRIBUTING.md) if you want to contribute to the repo. At a bare minimum, you need to fix your typos, run the black formatter, and actually test your code.

2024-05-03 01:49 UTC, rattus-rattus-rattus commented on plugins/clopen.py
> +    creatation_date: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP)
There is a typo - `creatation_date`?

2024-05-03 01:49 UTC, rattus-rattus-rattus commented on plugins/clopen.py
> +
It seems you didn't run Black. Please refer to [CONTRIBUTING.md](https://github.com/discord-math/bot/blob/main/CONTRIBUTING.md) if you want to contribute to the repo.

2024-05-03 01:49 UTC, rattus-rattus-rattus commented on plugins/clopen.py
> +                            await close(session, chanell, "Closed due to exceeding three hours")
More typos.

2024-05-03 01:52 UTC, Brandon-Huu commented on plugins/clopen.py
> +                            await close(session, chanell, "Closed due to exceeding three hours")
Fixed this earlier

2024-05-04 18:09 UTC, Brandon-Huu commented
I'll probably wont finish this. Too busy with school.

2024-05-04 18:09 UTC, closed without merging